apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-api-chart.fullname" . }}-config
  labels:
    {{- include "django-api-chart.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.config.DJANGO_SETTINGS_MODULE | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.DJANGO_ALLOWED_HOSTS | quote }}
  DJANGO_DEBUG: {{ .Values.config.DJANGO_DEBUG | quote }}
  TEST_DB_SSLMODE: {{ .Values.config.TEST_DB_SSLMODE | quote }}
  DEV: {{ .Values.config.DEV | quote }}
  DEBUG: {{ .Values.config.DEBUG | quote }}
