apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-api-chart.fullname" . }}
  labels:
    {{- include "django-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "django-api-chart.selectorLabels" . | nindent 4 }}
