apiVersion: v1
kind: Service
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  type: ClusterIP
  selector:
    app: django-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
