# Generated by Django 5.2.3 on 2025-07-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspected_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolved_by',
            field=models.CharField(max_length=100),
        ),
    ]
